services:
  auth-db:
    image: postgres:13.1-alpine
    container_name: postgres_db_container
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - dbSqlNetwork
    volumes:
      - ./data/postgresql/data/:/usr/data/postgres

networks:
  dbSqlNetwork:
    driver: bridge
volumes:
  pg_data:
    name: postgres